import subprocess


def test_pdf_generation(tmp_path):
    """
    Verify that a documentation PDF can be generated using Typst.
    """
    typst_file = tmp_path / "test.typ"
    pdf_path = tmp_path / "main.pdf"

    # Create a basic Typst document
    typst_file.write_text(
        "= Test Document\n\n"
        "This is a test PDF generated by Typst."
    )

    # Run typst compile
    subprocess.run(
        ["typst", "compile", str(typst_file), str(pdf_path)],
        check=True
    )

    # Check if file exists
    assert pdf_path.exists(), f"Documentation PDF not found at {pdf_path}"
    assert pdf_path.stat().st_size > 0, "Documentation PDF is empty"
